trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2 
      displayName: "Use .NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - task: DotNetCoreCLI@2
      displayName: "Build for $(buildConfiguration)"
      inputs:
        command: 'build'
        projects: '**/SimpleConsoleProgress.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: CopyFiles@2
      displayName: "Copy files to $(build.artifactstagingdirectory)"
      inputs:
        SourceFolder: '$(build.binariesdirectory)'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifacts"
      inputs:
        pathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: 'SimpleConsoleProgress'
    