trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2 
      displayName: "Use .NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - task: DotNetCoreCLI@2
      displayName: "Build for $(buildConfiguration)"
      inputs:
        command: 'build'
        projects: '**/SimpleConsoleProgress.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'SimpleConsoleProgress'
    