trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2 
      displayName: "Use .NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/ConsoleProgress.csproj'

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'ConsoleProgress'
    